import { useState } from 'react'
import Button from '../components/common/Button'
import { useSeatSelection } from '../contexts/SeatSelectionContext'
import { getEvent } from '../services/eventService'

export default function BookingReview() {
  const { selectedSeats, seatCount, subtotal, convenienceFee, total, activeEventId } = useSeatSelection()
  const [acceptedTerms, setAcceptedTerms] = useState(true)
  const event = getEvent(activeEventId)
  return <main className="page-shell"><section className="container review-page"><a className="back-link" href={`/events/${event.id}/seats`}>← Change seats</a><p className="eyebrow">Almost there</p><h1>Review your booking.</h1><div className="review-layout"><section className="review-main"><div className="review-card"><p className="eyebrow">Match</p><h2>{event.title}</h2><p className="muted">{event.day} {event.month} 2026 · {event.time} · {event.venue}, {event.city}</p></div><div className="review-card"><div className="review-card__heading"><div><p className="eyebrow">Your seats</p><h2>{seatCount} {seatCount === 1 ? 'seat' : 'seats'}</h2></div><a className="text-link" href={`/events/${event.id}/seats`}>Edit</a></div>{selectedSeats.length ? selectedSeats.map((seat) => <div className="review-seat" key={seat.seatId}><span><strong>{seat.seatId}</strong><small>{seat.tierLabel} · {seat.stand}, row {seat.row}</small></span><strong>₹{seat.price.toLocaleString('en-IN')}</strong></div>) : <p className="empty-state">No seats selected. Return to the map to choose your seats.</p>}</div><label className="terms"><input type="checkbox" checked={acceptedTerms} onChange={(event) => setAcceptedTerms(event.target.checked)} /> I agree to the booking terms and cancellation policy.</label></section><aside className="price-card"><p className="eyebrow">Price breakdown</p><div><span>Tickets</span><strong>₹{subtotal.toLocaleString('en-IN')}</strong></div><div><span>Convenience fee</span><strong>₹{convenienceFee.toLocaleString('en-IN')}</strong></div><div className="price-card__total"><span>Total</span><strong>₹{total.toLocaleString('en-IN')}</strong></div><Button href={seatCount && acceptedTerms ? '/booking-success' : undefined} disabled={!seatCount || !acceptedTerms}>Confirm booking <span aria-hidden="true">→</span></Button><small>Your seats are held for ten minutes while you complete checkout.</small></aside></div></section></main>
}
