import { useEffect } from 'react'
import Button from '../components/common/Button'

const categories = [
  ['Upper', 'From ₹600', 'A sweeping stadium view and match-day atmosphere.'],
  ['General', 'From ₹1,200', 'Close to the action with great sightlines.'],
  ['Club', 'From ₹2,500', 'A premium balance of comfort and view.'],
  ['Premium', 'From ₹5,000', 'Pavilion-adjacent seats with elevated service.'],
]

export default function EventDetails({ event }) {
  useEffect(() => { document.title = `${event.title} | SeatLY` }, [event.title])
  return <main className="event-detail"><section className={`event-detail__hero event-detail__hero--${event.imageTone}`}><div className="container"><a className="back-link back-link--light" href="/events">← All matches</a><div className="event-detail__hero-grid"><div><span className="event-badge">{event.category}</span><p className="event-detail__date">{event.day} {event.month} 2026 · {event.time}</p><div className="matchup matchup--large"><div><span className="team-mark team-mark--hero-home">{event.homeCode}</span><h1>{event.homeTeam}</h1></div><strong>VS</strong><div><span className="team-mark team-mark--hero-away">{event.awayCode}</span><h1>{event.awayTeam}</h1></div></div><p className="event-detail__venue">{event.venue}, {event.city} <span>·</span> {event.gates}</p></div><aside className="event-detail__availability"><span>SEATS ARE GOING</span><strong>{event.percentBooked}%</strong><p>{event.availability} for this match.</p><i><b style={{ width: `${event.percentBooked}%` }} /></i><Button href={`/events/${event.id}/seats`} variant="accent">Select seats <span aria-hidden="true">→</span></Button></aside></div></div></section><section className="container event-info-grid"><article><p className="eyebrow">About this match</p><h2>All the energy, from your ideal view.</h2><p>{event.description} Explore every available seating tier before booking — no guesswork, no static charts.</p><div className="event-info-grid__facts"><div><small>DATE</small><strong>{event.day} {event.month} 2026</strong></div><div><small>STARTS</small><strong>{event.time}</strong></div><div><small>VENUE</small><strong>{event.venue}</strong></div></div></article><aside><p className="eyebrow">Good to know</p><ul><li>Mobile tickets delivered after booking</li><li>Seats are held during checkout</li><li>Entry subject to venue policies</li></ul></aside></section><section className="seat-category-section"><div className="container"><div className="section-heading"><div><p className="eyebrow">Choose your experience</p><h2>Seats for every kind of fan.</h2></div><a className="text-link" href={`/events/${event.id}/seats`}>See live availability →</a></div><div className="category-grid">{categories.map(([tier, price, copy], index) => <article className={`category-card category-card--${index}`} key={tier}><span>{tier}</span><h3>{price}</h3><p>{copy}</p><a href={`/events/${event.id}/seats`}>Browse seats <b>→</b></a></article>)}</div></div></section><div className="mobile-match-cta"><div><strong>From ₹{event.from.toLocaleString('en-IN')}</strong><span>{event.availability}</span></div><a className="button button--accent" href={`/events/${event.id}/seats`}>Select seats</a></div></main>
}
